### ISSUE TITLE
Filter high- and low-pass separately instead of bandpass (line 34 in KEH_test.m)

### ISSUE THREAD

**Issue by demaddis** [juliankeil/ECoG#1]
Different transition bandwidths are required for high- and low-pass, so should be filtered separately. 

See: https://sccn.ucsd.edu/wiki/Firfilt_FAQ#Q._Should_we_prefer_separate_high-_and_lowpass_filters_over_bandpass_filters.3F

**Comment by juliankeil** [comment]
I updated the code to include two separate filter stages. The question is, if I coded the call correctly (I'll test this tuesday), and whether the order of the filters matters (first low, then high or the other way around)?
I also noticed that I had sloppily set the code to always overwrite the EEG_filt-structure with every call, effectively resulting in only the notch-filter being applied to the EEG_filt structure.
